workflows:
  derby-bins:
    name: Derby Bins
    max_build_duration: 30
    environment:
      flutter: stable
      ubuntu: 24.04
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
