workflows:
  derby-bins:
    name: Derby Bins
    max_build_duration: 30
    environment:
      flutter: stable
      ubuntu: 24.04
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    android_signing:
      - keystore: $KEYSTORE_BASE64
        store_password: $KEYSTORE_PASSWORD
        key_alias: $KEY_ALIAS
        key_password: $KEY_PASSWORD
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
